### ISSUE TITLE
loading txt file/project topic change

### ISSUE THREAD

**Issue by oatkinsonr** [oatkinsonr/Soc_513_Final_Project#1]
@AaronGullickson 

I have pushed my maternal mortality by census region data to git. I was thinking of how I could use this data since I have it already and because the state level data is so suppressed. IPUMS has data at the census region level regarding the gender of the respondents primary care physician. So, I was thinking I could do an analysis of regions with higher levels of female primary care doctors to regions with higher levels of male primary care doctors, the hypothesis being that regions where there are higher numbers of female primary care docs the maternal mortality rates will be lower. Would this work?

**Comment by oatkinsonr** [comment]
@AaronGullickson 

Also, I pushed the maternal mortality data as a txt file because I couldn't figure out how to load a txt file into R

**Comment by AaronGullickson** [comment]
We got this working in OH with the `read_tsv` command in `readr` so I am closing.
