### ISSUE TITLE
file too big

### ISSUE THREAD

**Issue by oatkinsonr** [oatkinsonr/Soc_513_Final_Project#2]
@AaronGullickson I figured out how to write in my txt file I think. But my data from IPUMS about the gender of doctors by region is too big so I can't push it. 

I just decided to go ahead with trying to read in the data for the new question about the relationship between maternal mortality and the number of female doctors by census region so I could move ahead with the project. I still have all the data for the state by state analysis about maternal mortality and drug codes, but it seems like because so much data is suppressed it would be difficult to move forward with that particular question.

**Comment by AaronGullickson** [comment]
@oatkinsonr 

Did you commit the IPUMS data? My guess is you are using too many years of data and we can probably fix it easy enough, but it will be harder if you already committed.

**Comment by AaronGullickson** [comment]
@oatkinsonr Also, I am not sure the suppression is that bad in your case. You will lose some of the smaller states, but it looks like you could get a sample of at least 30 states going back to around 2006-07 or so. There are also [some techniques](https://ajph.aphapublications.org/doi/abs/10.2105/AJPH.2014.301900) for [imputing missing values](https://gking.harvard.edu/amelia).

**Comment by AaronGullickson** [comment]
@oatkinsonr Based on our conversation today. I will go ahead and close this.
