### ISSUE TITLE
Help preparing analytical dataset

### ISSUE THREAD

**Issue by oatkinsonr** [oatkinsonr/Soc_513_Final_Project#3]
@AaronGullickson is there a time I could come by your office today to get some help preparing my analytical dataset? I was unable to come to your office hours on Wednesday because of other obligations.

**Comment by oatkinsonr** [comment]
@AaronGullickson and if you don't have time I can just push what I have done so far to git and see if you could help me out that way. Thanks!

**Comment by AaronGullickson** [comment]
@oatkinsonr Sorry Olivia, today was a crazy day and I am just sitting down to check my email. If you want to stop by I could give you a little time. Or you can just push to github and let me know where you need help.
