### ISSUE TITLE
calculated mmr

### ISSUE THREAD

**Issue by oatkinsonr** [oatkinsonr/Soc_513_Final_Project#5]
@AaronGullickson I merged the births and deaths and calculated the maternal mortality ratio. Could you look it over and see if I did it correctly? 

Thanks!!

**Comment by AaronGullickson** [comment]
@oatkinsonr It looks good, except that you need to save the `mmr` variable back int to the `mm` dataset. Right now you have it floating out there as a vector by itself.

```r
mm$mmr <- (mm$deaths/mm$births)
```
