### ISSUE TITLE
template issues

### ISSUE THREAD

**Issue by oatkinsonr** [oatkinsonr/Soc_513_Final_Project#8]
hi @AaronGullickson I just pushed my final paper. It is basically done, but I am having trouble with the template. It isn't showing the thanks, affiliation, keywords, or abstract section when I knit to pdf.

**Comment by AaronGullickson** [comment]
@oatkinsonr You did a number on the yaml header. The `fig.cap="center"` in the figure code chunks was also causing problems. I fixed both things in commit ddba4504cc1fe7d5ead73024da7a1328029170dc. You should be able to pull it and knit to PDF.
